TrackG4: ReadOut Class Reference
ReadOut Class Reference
This class manages the readout of the simulation.
#include <ReadOut.hh>
Public Member Functions
~ReadOut ()
G4double closest_value (std::vector< G4double > vec, G4double value)
Function that, given a vector and a value, find the closest value in the vector.
G4double closest_channel (G4double hit_position, std::vector< G4double > modulePositions, G4double pitchOnAxis)
Function to find the position on the axis of the pixel/strip channel that was hit.
G4double closest_channel (G4double hit_position, const std::string &axis, const std::string &moduleType)
Function to find the position on the axis of the pixel/strip channel that was hit.
G4double closest_channel (G4double hit_position, const std::string &axis, int layerNumber)
Function to find the position on the axis of the pixel/strip channel that was hit.
Static Public Member Functions
static ReadOut * GetInstance ()
Get the Instance object If the instance is not created, it will be created If the instance is already created, it will be returned the pointer to the previous instance.
Private Member Functions
ReadOut ()
Private constructor (because is a singleton)
Private Attributes
std::vector< G4double > xModulePosition
Position of the center of the silicon modules on the x axis.
std::vector< G4double > yModulePosition
Position of the center of the silicon modules on the y axis.
std::vector< G4double > zModulePosition
Position of the center of the silicon modules on the z axis.
Static Private Attributes
static ReadOut * instance = nullptr
Single istance of the class.
Detailed Description
This class manages the readout of the simulation.
This class is responsible to the transformation of the real hits into the position of the readout channels.
As the other managers used in the simulation, this class is a singleton
Definition at line 19 of file ReadOut.hh.
Constructor & Destructor Documentation
ReadOut()
ReadOut::ReadOut () private
Private constructor (because is a singleton)
Initialize the modulePosition vectors with the values of the module position This avoid to compute the module position every time the function is called
Definition at line 13 of file ReadOut.cpp.
Referenced by GetInstance().
~ReadOut()
ReadOut::~ReadOut ()
Definition at line 18 of file ReadOut.cpp.
Member Function Documentation
closest_channel() [1/3]
G4double ReadOut::closest_channel (G4double hit_position, const std::string & axis, const std::string & moduleType)
Function to find the position on the axis of the pixel/strip channel that was hit.
Parameters
hit_position Real position of the hit
axis Axis on which we want to find the channel ("x", "y" or "z")
moduleType Module type ("pixel" or "strip")
Returns
G4double Postion on the given axis of the pixel/strip channel that was hit
It is just a wrapper to the function G4double closest_channel(G4double hit_position, std::vector<G4double> modulePositions, G4double pitchOnAxis)
Definition at line 78 of file ReadOut.cpp.
References closest_channel(), closest_value(), GeometryParameters::moduleDimZ, ReadOutParameters::pixelDimX, ReadOutParameters::pixelDimY, GeometryParameters::pixelStripSpacing, ReadOutParameters::stripDimX, ReadOutParameters::stripDimY, xModulePosition, yModulePosition, and zModulePosition.
closest_channel() [2/3]
G4double ReadOut::closest_channel (G4double hit_position, const std::string & axis, int layerNumber)
Function to find the position on the axis of the pixel/strip channel that was hit.
Parameters
hit_position Real position of the hit
axis Axis on which we want to find the channel ("x", "y" or "z")
layerNumber Number of the layer that was hit (the odds are pixels, the evens are strips)
Returns
G4double Postion on the given axis of the pixel/strip channel that was hit
It is just a wrapper to the function G4double closest_channel(G4double hit_position, std::string axis, std::string moduleType)
Definition at line 125 of file ReadOut.cpp.
References closest_channel().
closest_channel() [3/3]
G4double ReadOut::closest_channel (G4double hit_position, std::vector< G4double > modulePositions, G4double pitchOnAxis)
Function to find the position on the axis of the pixel/strip channel that was hit.
Parameters
hit_position Real position of the hit
modulePositions Position of the center of the all modules on the axis
pitchOnAxis Pitch of the pixel/strip on the axis
Returns
G4double Postion on the given axis of the pixel/strip channel that was hit
The function finds the position of the center of the closest silicon module on a given axis and then translate the hit position on the frame of the module.
The position of the channel in this frame is computed by the formula: \((\floor{h/p}+0.5)*p \) where:
h is the hit position in the frame of the module
p is the pitch of the pixel/strip on the given axis
The value obtained is translated back to the original frame of the detector
Achtung: this function works only if the number of channel on the given axis is even. If the number of channels is odd, there will be an offset of 0.5 of the pitch of the channel on the axis.
Definition at line 67 of file ReadOut.cpp.
References closest_value().
Referenced by closest_channel(), MySensitiveDetector::ProcessHits(), and TEST_CASE().
closest_value()
G4double ReadOut::closest_value (std::vector< G4double > vec, G4double value)
Function that, given a vector and a value, find the closest value in the vector.
Parameters
vec The vector in which we search the closest value
value The value we want to find the closest value in the vector
Returns
G4double The closest value in the vector to "value"
The closest value is found sorting the vector and then finding the closest value iterating on the vector. When the distance between the element of the array and the value is greater than the previous distance, the for loop is broken and the element of the vector is returned.
Definition at line 33 of file ReadOut.cpp.
Referenced by closest_channel(), and TEST_CASE().
GetInstance()
ReadOut * ReadOut::GetInstance () static
Get the Instance object If the instance is not created, it will be created If the instance is already created, it will be returned the pointer to the previous instance.
Returns
ReadOut*
Definition at line 20 of file ReadOut.cpp.
References instance, and ReadOut().
Referenced by MySensitiveDetector::ProcessHits(), and TEST_CASE().
Member Data Documentation
instance
ReadOut * ReadOut::instance = nullptr static private
Single istance of the class.
Definition at line 41 of file ReadOut.hh.
Referenced by GetInstance().
xModulePosition
std::vector<G4double> ReadOut::xModulePosition private
Position of the center of the silicon modules on the x axis.
Definition at line 24 of file ReadOut.hh.
Referenced by closest_channel().
yModulePosition
std::vector<G4double> ReadOut::yModulePosition private
Position of the center of the silicon modules on the y axis.
Definition at line 28 of file ReadOut.hh.
Referenced by closest_channel().
zModulePosition
std::vector<G4double> ReadOut::zModulePosition private
Position of the center of the silicon modules on the z axis.
Definition at line 32 of file ReadOut.hh.
Referenced by closest_channel().
The documentation for this class was generated from the following files:
/home/pviscone/Desktop/TrackG4/include/ReadOut.hh
/home/pviscone/Desktop/TrackG4/src/ReadOut.cpp