TrackG4: MySensitiveDetector Class Reference
MySensitiveDetector Class Reference
The class that manages the sensitive detector.
#include <SensitiveDetector.hh>
Public Member Functions
MySensitiveDetector (G4String name)
Constructor of the sensitive detector.
~MySensitiveDetector ()
Destructor of the sensitive detector.
Private Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Method that is called when a step is detected.
Detailed Description
The class that manages the sensitive detector.
The sensitive detector is the volume that is used to detect the particles and save the data.
Definition at line 15 of file SensitiveDetector.hh.
Constructor & Destructor Documentation
MySensitiveDetector()
MySensitiveDetector::MySensitiveDetector (G4String name)
Constructor of the sensitive detector.
Parameters
name The name of the sensitive detector.
Definition at line 3 of file SensitiveDetector.cc.
~MySensitiveDetector()
MySensitiveDetector::~MySensitiveDetector ()
Destructor of the sensitive detector.
Definition at line 6 of file SensitiveDetector.cc.
Member Function Documentation
ProcessHits()
G4bool MySensitiveDetector::ProcessHits (G4Step * aStep, G4TouchableHistory * R0hist) private virtual
Method that is called when a step is detected.
This method runs at every step of the particle in the sensitive detector and it is used to save the data.
Parameters
aStep The step that is detected.
R0hist The history of the step.
The data stored at each step is:
EventID
TrackID
ParticleID
ParticleName
EnergyDeposited (keV)
posX X position of the channel that was hit (mm)
posY Y position of the channel that was hit (mm)
posZ Z position of the channel that was hit (mm)
Layer layer that the hit is in (odd layer are pixels module, even layer are strips module)
Definition at line 22 of file SensitiveDetector.cc.
References ReadOut::closest_channel(), Event::detectorData, TriggerParameters::energyCut, DetectorData::EnergyDeposited, DataManager::GetEvent(), DataManagerMT::GetInstance(), ReadOut::GetInstance(), DataManagerMT::GetSTDataManager(), DetectorData::Layer, DetectorData::ParticleID, DetectorData::posX, DetectorData::posY, DetectorData::posZ, and DetectorData::TrackID.
The documentation for this class was generated from the following files:
/home/pviscone/Desktop/TrackG4/include/SensitiveDetector.hh
/home/pviscone/Desktop/TrackG4/src/SensitiveDetector.cc