TrackG4: Catch::StringMaker< T, typename > Struct Template Reference
Catch::StringMaker< T, typename > Struct Template Reference
#include <catch.hpp>
Static Public Member Functions
template<typename Fake = T>
static std::enable_if<::Catch::Detail::IsStreamInsertable< Fake >::value, std::string >::type convert (const Fake &value)
template<typename Fake = T>
static std::enable_if<!::Catch::Detail::IsStreamInsertable< Fake >::value, std::string >::type convert (const Fake &value)
Detailed Description
template<typename T, typename = void>
struct Catch::StringMaker< T, typename >
Definition at line 1615 of file catch.hpp.
Member Function Documentation
convert() [1/2]
template<typename T , typename = void> template<typename Fake = T> static std::enable_if<::Catch::Detail::IsStreamInsertable< Fake >::value, std::string >::type Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 1619 of file catch.hpp.
References Catch::ReusableStringStream::str(), and Catch::Generators::value().
convert() [2/2]
template<typename T , typename = void> template<typename Fake = T> static std::enable_if<!::Catch::Detail::IsStreamInsertable< Fake >::value, std::string >::type Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 1630 of file catch.hpp.
References Catch::Detail::convertUnstreamable(), and Catch::Generators::value().
The documentation for this struct was generated from the following file:
/home/pviscone/Desktop/TrackG4/test/catch.hpp