TrackG4: test/DataManagerMT/DataManagerMTTest.cpp File Reference
DataManagerMTTest.cpp File Reference
#include "DataManagerMT.hh"
#include "../catch.hpp"
#include "UserParameters.hh"
#include <cppitertools/combinations.hpp>
#include <thread>
Functions
TEST_CASE ("Verify that DataManagerMT is a singleton")
TEST_CASE ("Verify that DataManagerMt has a vector of different instances of DataManager")
Function Documentation
TEST_CASE() [1/2]
TEST_CASE ("Verify that DataManagerMt has a vector of different instances of DataManager")
Definition at line 13 of file DataManagerMTTest.cpp.
References DataManagerMT::GetInstance(), DataManagerMT::GetSTDataManager(), and SystemParameters::nThreads.
TEST_CASE() [2/2]
TEST_CASE ("Verify that DataManagerMT is a singleton")
Definition at line 7 of file DataManagerMTTest.cpp.
References DataManagerMT::GetInstance().