TrackG4: test/ReadOut/ReadOutTest.cpp File Reference
ReadOutTest.cpp File Reference
#include "ReadOut.hh"
#include "../catch.hpp"
#include "cppitertools/enumerate.hpp"
#include "cppitertools/zip.hpp"
#include <algorithm>
#include <iostream>
#include <string>
#include <vector>
Functions
TEST_CASE ("Test the closest_value function")
TEST_CASE ("Test the read out on single axis")
TEST_CASE ("Test the read out passing the strings")
Function Documentation
TEST_CASE() [1/3]
TEST_CASE ("Test the closest_value function")
Definition at line 11 of file ReadOutTest.cpp.
References ReadOut::closest_value(), and ReadOut::GetInstance().
TEST_CASE() [2/3]
TEST_CASE ("Test the read out on single axis")
Definition at line 40 of file ReadOutTest.cpp.
References ReadOut::closest_channel(), and ReadOut::GetInstance().
TEST_CASE() [3/3]
TEST_CASE ("Test the read out passing the strings")
Definition at line 55 of file ReadOutTest.cpp.
References ReadOut::closest_channel(), and ReadOut::GetInstance().