TrackG4: DataManager Class Reference
DataManager Class Reference
This class manage TFiles and TTrees to store the data exploiting the Event class structure.
#include <DataManager.hh>
Public Member Functions
~DataManager ()
Singleton destructor.
TFile * OpenFile (std::string filename, std::string option="")
Open the TFile.
TTree * CreateTree (std::string name)
Create a Tree object.
TFile * GetFile ()
Return the pointer to the file of the DataManager singleton.
TTree * GetTree ()
Return the pointer to the tree of the DataManager singleton.
Event * GetEvent ()
Return the pointer to the event of the DataManager singleton.
Static Public Member Functions
static DataManager * GetInstance ()
Method to construct the singleton. The first time create the singleton, then return the pointer to it.
Private Member Functions
DataManager ()
Private constructor.
Private Attributes
TFile * file
The file where the data is stored.
TTree * tree
The tree where the data is stored.
Event * event
The event class object used to store data.
Static Private Attributes
static DataManager * instance = nullptr
pointer to the single instance of the class.
Friends
class DataManagerMT
Class used to use the DataManager class in multithreading mode.
Detailed Description
This class manage TFiles and TTrees to store the data exploiting the Event class structure.
This class is a singleton
Definition at line 13 of file DataManager.hh.
Constructor & Destructor Documentation
DataManager()
DataManager::DataManager () private
Private constructor.
The constructor is private because the class is a singleton.
Definition at line 5 of file DataManager.cc.
References file, and tree.
Referenced by GetInstance().
~DataManager()
DataManager::~DataManager ()
Singleton destructor.
Definition at line 20 of file DataManager.cc.
References instance.
Member Function Documentation
CreateTree()
TTree * DataManager::CreateTree (std::string name)
Create a Tree object.
Parameters
name name of the TTree
Returns
TTree* the pointer to the TTree
Definition at line 31 of file DataManager.cc.
References event, and tree.
Referenced by MyRunAction::BeginOfRunAction().
GetEvent()
Event * DataManager::GetEvent ()
Return the pointer to the event of the DataManager singleton.
This class has to be filled with the data. At the end of each event this object has to be written in the tree and cleared
Returns
Event* the pointer to the event
Definition at line 47 of file DataManager.cc.
References event.
Referenced by MyEventAction::EndOfEventAction(), MyPrimaryGenerator::GeneratePrimaries(), and MySensitiveDetector::ProcessHits().
GetFile()
TFile * DataManager::GetFile ()
Return the pointer to the file of the DataManager singleton.
Returns
TFile* the pointer to the file
Definition at line 39 of file DataManager.cc.
References file.
Referenced by MyRunAction::EndOfRunAction().
GetInstance()
DataManager * DataManager::GetInstance () static
Method to construct the singleton. The first time create the singleton, then return the pointer to it.
Returns
DataManager* the pointer to the singleton instance
Definition at line 12 of file DataManager.cc.
References DataManager(), and instance.
Referenced by TEST_CASE().
GetTree()
TTree * DataManager::GetTree ()
Return the pointer to the tree of the DataManager singleton.
Returns
TTree* the pointer to the tree
Definition at line 43 of file DataManager.cc.
References tree.
Referenced by MyEventAction::EndOfEventAction().
OpenFile()
TFile * DataManager::OpenFile (std::string filename, std::string option = "")
Open the TFile.
Parameters
fileName the name of the file
option the mode of the file
Returns
TFile* the pointer to the TFile
Definition at line 25 of file DataManager.cc.
References file.
Referenced by MyRunAction::BeginOfRunAction().
Friends And Related Function Documentation
DataManagerMT
friend class DataManagerMT friend
Class used to use the DataManager class in multithreading mode.
A Singleton object is not thread safe.
To be thread safe the strategy usually adopted by geant is to use a different file for each working thread.
With a singleton we cannot use multiple files so we define a friend class DataManagerMT (another singleton) that is able to create multiple instances of DataManager, one for each working thread
Definition at line 56 of file DataManager.hh.
Member Data Documentation
event
Event* DataManager::event private
The event class object used to store data.
Definition at line 44 of file DataManager.hh.
Referenced by CreateTree(), and GetEvent().
file
TFile* DataManager::file private
The file where the data is stored.
Definition at line 32 of file DataManager.hh.
Referenced by DataManager(), GetFile(), and OpenFile().
instance
DataManager * DataManager::instance = nullptr static private
pointer to the single instance of the class.
Definition at line 26 of file DataManager.hh.
Referenced by GetInstance(), and ~DataManager().
tree
TTree* DataManager::tree private
The tree where the data is stored.
Definition at line 38 of file DataManager.hh.
Referenced by CreateTree(), DataManager(), and GetTree().
The documentation for this class was generated from the following files:
include/DataManager.hh
src/DataManager.cc