TrackG4: DataManagerMT Class Reference
DataManagerMT Class Reference
Singleton class that manage the data in multithreading mode.
#include <DataManagerMT.hh>
Public Member Functions
~DataManagerMT ()
Destroy the DataManagerMT object.
DataManager * GetSTDataManager (int i)
Return the DataManager object used by the i-th thread.
Static Public Member Functions
static DataManagerMT * GetInstance ()
Get the instance of the class. The first time create the singleton, then return the pointer to it.
Private Member Functions
DataManagerMT ()
Private constructor.
Private Attributes
int nThreads = SystemParameters::nThreads
The number of thread used to run the simulation.
std::vector< DataManager * > dataManagerVector
The vector of DataManager objects.
Static Private Attributes
static DataManagerMT * instanceMT = nullptr
Private constructor.
Detailed Description
Singleton class that manage the data in multithreading mode.
This class is a friend class of DataManager.
This class is a singleton container for multiple instance of DataManager
Definition at line 15 of file DataManagerMT.hh.
Constructor & Destructor Documentation
DataManagerMT()
DataManagerMT::DataManagerMT () private
Private constructor.
The constructor is private because the class is a singleton.
Definition at line 5 of file DataManagerMT.cc.
References dataManagerVector, and nThreads.
Referenced by GetInstance().
~DataManagerMT()
DataManagerMT::~DataManagerMT ()
Destroy the DataManagerMT object.
Definition at line 15 of file DataManagerMT.cc.
References dataManagerVector, instanceMT, and nThreads.
Member Function Documentation
GetInstance()
DataManagerMT * DataManagerMT::GetInstance () static
Get the instance of the class. The first time create the singleton, then return the pointer to it.
Returns
The instance of the single class object.
Definition at line 25 of file DataManagerMT.cc.
References DataManagerMT(), and instanceMT.
Referenced by MyRunAction::BeginOfRunAction(), MyEventAction::EndOfEventAction(), MyRunAction::EndOfRunAction(), MyPrimaryGenerator::GeneratePrimaries(), MySensitiveDetector::ProcessHits(), and TEST_CASE().
GetSTDataManager()
DataManager * DataManagerMT::GetSTDataManager (int i)
Return the DataManager object used by the i-th thread.
Parameters
i threadId
Returns
DataManager*
Definition at line 35 of file DataManagerMT.cc.
References dataManagerVector.
Referenced by MyRunAction::BeginOfRunAction(), MyEventAction::EndOfEventAction(), MyRunAction::EndOfRunAction(), MyPrimaryGenerator::GeneratePrimaries(), MySensitiveDetector::ProcessHits(), and TEST_CASE().
Member Data Documentation
dataManagerVector
std::vector<DataManager *> DataManagerMT::dataManagerVector private
The vector of DataManager objects.
The vector is used to store the DataManager objects. Each element of the vector contain a DataManager object used by the same thread
Definition at line 40 of file DataManagerMT.hh.
Referenced by DataManagerMT(), GetSTDataManager(), and ~DataManagerMT().
instanceMT
DataManagerMT * DataManagerMT::instanceMT = nullptr static private
Private constructor.
The constructor is private because the class is a singleton.
Definition at line 23 of file DataManagerMT.hh.
Referenced by GetInstance(), and ~DataManagerMT().
nThreads
int DataManagerMT::nThreads = SystemParameters::nThreads private
The number of thread used to run the simulation.
The number of thread is set in the UserParameters file
Definition at line 31 of file DataManagerMT.hh.
Referenced by DataManagerMT(), and ~DataManagerMT().
The documentation for this class was generated from the following files:
include/DataManagerMT.hh
src/DataManagerMT.cc