TrackG4: MyRunAction Class Reference
MyRunAction Class Reference
The class that manages the run action.
#include <RunAction.hh>
Public Member Functions
MyRunAction ()
Constructor of the run action.
virtual ~MyRunAction ()
Destructor of the run action.
virtual void BeginOfRunAction (const G4Run *)
Method that is called at the beginning of the run.
virtual void EndOfRunAction (const G4Run *)
Method that is called at the end of the run.
Detailed Description
The class that manages the run action.
In this class we define the structure of the output file to store the sensitive detector data.
Definition at line 21 of file RunAction.hh.
Constructor & Destructor Documentation
MyRunAction()
MyRunAction::MyRunAction ()
Constructor of the run action.
Definition at line 3 of file RunAction.cc.
~MyRunAction()
MyRunAction::~MyRunAction () virtual
Destructor of the run action.
Definition at line 5 of file RunAction.cc.
Member Function Documentation
BeginOfRunAction()
void MyRunAction::BeginOfRunAction (const G4Run *) virtual
Method that is called at the beginning of the run.
This method runs at the beginning of the run and it is used to initialize the analysis manager and define the output file.
Parameters
run The run that is initialized.
Definition at line 7 of file RunAction.cc.
References DataManager::CreateTree(), DataManagerMT::GetInstance(), DataManagerMT::GetSTDataManager(), DataManager::OpenFile(), and OutputParameters::outputFileName.
EndOfRunAction()
void MyRunAction::EndOfRunAction (const G4Run *) virtual
Method that is called at the end of the run.
This method runs at the end of the run and it is used to save the data in the output file and close the file.
Parameters
run The run that is finished.
Definition at line 23 of file RunAction.cc.
References DataManager::GetFile(), DataManagerMT::GetInstance(), and DataManagerMT::GetSTDataManager().
The documentation for this class was generated from the following files:
include/RunAction.hh
src/RunAction.cc