TrackG4: MyEventAction Class Reference
MyEventAction Class Reference
This class manage the user action at each event.
#include <EventAction.hh>
Public Member Functions
MyEventAction ()
virtual ~MyEventAction ()
virtual void BeginOfEventAction (const G4Event *)
Function that is called at the beginning of the event.
virtual void EndOfEventAction (const G4Event *)
Function that is called at the end of each event.
Detailed Description
This class manage the user action at each event.
Definition at line 13 of file EventAction.hh.
Constructor & Destructor Documentation
MyEventAction()
MyEventAction::MyEventAction ()
Definition at line 3 of file EventAction.cc.
~MyEventAction()
MyEventAction::~MyEventAction () virtual
Definition at line 5 of file EventAction.cc.
Member Function Documentation
BeginOfEventAction()
void MyEventAction::BeginOfEventAction (const G4Event *) virtual
Function that is called at the beginning of the event.
Parameters
event Pointer to the event that is currently running.
Definition at line 7 of file EventAction.cc.
EndOfEventAction()
void MyEventAction::EndOfEventAction (const G4Event *) virtual
Function that is called at the end of each event.
Parameters
event Pointer to the event that is currently running.
At the end of each action this function fill the tree and clear the event object
If there aren't at least two hit in two different layers, the event is not saved
Definition at line 16 of file EventAction.cc.
References Event::Clear(), Event::detectorData, DataManager::GetEvent(), DataManagerMT::GetInstance(), DataManagerMT::GetSTDataManager(), DataManager::GetTree(), and DetectorData::Layer.
The documentation for this class was generated from the following files:
include/EventAction.hh
src/EventAction.cc