name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    name: Build 
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install ccache
      run: sudo apt install -y ccache
      
    - name: export path
      run: export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
      
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        verbose: 2
    
    - name: Create build folder
      # Create build folder if not exist
      run: mkdir -p build
      
    - name: cd build
      run: cd build
      
    - name: CMake
      # Run cmake
      run: cmake -DBUILD_DOC=OFF ${{github.workspace}}
      
    - name: make
      run: make -j8
      
    - name: Tests
      run: ./tests_executable -s
      

